name: Makefile CI

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]

env:
  TAG: linux
  VERSION: 1.5.0
  
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: goto-bus-stop/setup-zig@v2
    
    - name: Build release
      run: make build-exe
      
    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: linux-${{ env.VERSION }}
        release_name: ${{ env.VERSION }}
        draft: true
        prerelease: false

    - name: Create release archive
      run: tar -cvzf zig-search_${{ env.VERSION }}_release.tar.gz bin/zig-search
    
    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./zig-search_${{ env.VERSION }}_release.tar.gz
        asset_name: zig-search_${{ env.VERSION }}_release.tar.gz
        asset_content_type: application/tar+gzip

    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2

      - name: Build release
        run: zig build-exe src/main.zig --name zig-search --build-id=sha1 -static

      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: windows-${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          draft: true
          prerelease: false
